const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, '../src/data/nihongo-lessons.ts');
let code = fs.readFileSync(filePath, 'utf8');

const extraWords = {
  1: [
    { word: 'あの方', reading: 'あのかた', romaji: 'ano kata', meaning: 'Vị kia (lịch sự của あの人)', type: 'Đại từ' },
    { word: '～人', reading: '～じん', romaji: '~jin', meaning: 'Người nước ~', type: 'Hậu tố' },
    { word: '～歳', reading: '～さい', romaji: '~sai', meaning: '~ tuổi', type: 'Hậu tố' },
    { word: '何歳', reading: 'なんさい', romaji: 'nansai', meaning: 'Mấy tuổi', type: 'Từ để hỏi' },
    { word: 'おいくつ', reading: 'おいくつ', romaji: 'oikutsu', meaning: 'Mấy tuổi (lịch sự)', type: 'Từ để hỏi' },
    { word: 'お名前は？', reading: 'おなまえは？', romaji: 'o-namae wa?', meaning: 'Tên bạn là gì?', type: 'Mẫu câu' },
    { word: 'こちらは～さんです', reading: 'こちらは～さんです', romaji: 'kochira wa ~san desu', meaning: 'Đây là anh/chị ~', type: 'Mẫu câu' },
    { word: '～から来ました', reading: '～からきました', romaji: '~kara kimashita', meaning: 'Đến từ ~', type: 'Mẫu câu' },
    { word: 'アメリカ', reading: 'アメリカ', romaji: 'Amerika', meaning: 'Mỹ', type: 'Danh từ' },
    { word: 'イギリス', reading: 'イギリス', romaji: 'Igirisu', meaning: 'Anh', type: 'Danh từ' },
    { word: 'インド', reading: 'インド', romaji: 'Indo', meaning: 'Ấn Độ', type: 'Danh từ' },
    { word: '韓国', reading: 'かんこく', romaji: 'Kankoku', meaning: 'Hàn Quốc', type: 'Danh từ' },
    { word: '中国', reading: 'ちゅうごく', romaji: 'Chuugoku', meaning: 'Trung Quốc', type: 'Danh từ' },
    { word: '日本', reading: 'にほん', romaji: 'Nihon', meaning: 'Nhật Bản', type: 'Danh từ' }
  ],
  2: [
    { word: '新聞', reading: 'しんぶん', romaji: 'shinbun', meaning: 'Báo', type: 'Danh từ' },
    { word: '手帳', reading: 'てちょう', romaji: 'techou', meaning: 'Sổ tay', type: 'Danh từ' },
    { word: 'カード', reading: 'カード', romaji: 'kaado', meaning: 'Thẻ', type: 'Danh từ' },
    { word: '鉛筆', reading: 'えんぴつ', romaji: 'enpitsu', meaning: 'Bút chì', type: 'Danh từ' },
    { word: 'シャープペンシル', reading: 'シャープペンシル', romaji: 'shaapupenshiru', meaning: 'Bút chì kim', type: 'Danh từ' },
    { word: 'テレビ', reading: 'テレビ', romaji: 'terebi', meaning: 'Tivi', type: 'Danh từ' },
    { word: 'ラジオ', reading: 'ラジオ', romaji: 'rajio', meaning: 'Radio', type: 'Danh từ' },
    { word: '自動車', reading: 'じどうしゃ', romaji: 'jidousha', meaning: 'Ô tô', type: 'Danh từ' },
    { word: '机', reading: 'つくえ', romaji: 'tsukue', meaning: 'Bàn', type: 'Danh từ' },
    { word: 'いす', reading: 'いす', romaji: 'isu', meaning: 'Ghế', type: 'Danh từ' },
    { word: 'チョコレート', reading: 'チョコレート', romaji: 'chokoreeto', meaning: 'Sô-cô-la', type: 'Danh từ' },
    { word: 'コーヒー', reading: 'コーヒー', romaji: 'koohii', meaning: 'Cà phê', type: 'Danh từ' },
    { word: '英語', reading: 'えいご', romaji: 'eigo', meaning: 'Tiếng Anh', type: 'Danh từ' },
    { word: '日本語', reading: 'にほんご', romaji: 'nihongo', meaning: 'Tiếng Nhật', type: 'Danh từ' },
    { word: '～語', reading: '～ご', romaji: '~go', meaning: 'Tiếng ~', type: 'Hậu tố' },
    { word: '何', reading: 'なん', romaji: 'nan', meaning: 'Cái gì', type: 'Từ để hỏi' },
    { word: 'そう', reading: 'そう', romaji: 'sou', meaning: 'Đúng vậy', type: 'Phó từ' },
    { word: 'あのう', reading: 'あのう', romaji: 'anou', meaning: 'À, ờ (ngập ngừng)', type: 'Cảm thán' },
    { word: 'ほんの気持ちです', reading: 'ほんのきもちです', romaji: 'hon no kimochi desu', meaning: 'Chút lòng thành', type: 'Mẫu câu' },
    { word: 'どうぞ', reading: 'どうぞ', romaji: 'douzo', meaning: 'Xin mời', type: 'Mẫu câu' },
    { word: 'どうも', reading: 'どうも', romaji: 'doumo', meaning: 'Cảm ơn', type: 'Mẫu câu' },
    { word: 'これからお世話になります', reading: 'これからおせわになります', romaji: 'korekara osewani narimasu', meaning: 'Từ nay mong được giúp đỡ', type: 'Mẫu câu' },
    { word: 'こちらこそよろしく', reading: 'こちらこそよろしく', romaji: 'kochirakoso yoroshiku', meaning: 'Chính tôi mới mong được giúp đỡ', type: 'Mẫu câu' }
  ],
  3: [
    { word: '教室', reading: 'きょうしつ', romaji: 'kyoushitsu', meaning: 'Phòng học', type: 'Danh từ' },
    { word: '食堂', reading: 'しょくどう', romaji: 'shokudou', meaning: 'Nhà ăn', type: 'Danh từ' },
    { word: '事務所', reading: 'じむしょ', romaji: 'jimusho', meaning: 'Văn phòng', type: 'Danh từ' },
    { word: '会議室', reading: 'かいぎしつ', romaji: 'kaigishitsu', meaning: 'Phòng họp', type: 'Danh từ' },
    { word: '受付', reading: 'うけつけ', romaji: 'uketsuke', meaning: 'Quầy tiếp tân', type: 'Danh từ' },
    { word: 'ロビー', reading: 'ロビー', romaji: 'robii', meaning: 'Sảnh', type: 'Danh từ' },
    { word: '部屋', reading: 'へや', romaji: 'heya', meaning: 'Căn phòng', type: 'Danh từ' },
    { word: 'トイレ', reading: 'トイレ', romaji: 'toire', meaning: 'Nhà vệ sinh', type: 'Danh từ' },
    { word: 'おてあらい', reading: 'おてあらい', romaji: 'otearai', meaning: 'Nhà vệ sinh (lịch sự)', type: 'Danh từ' },
    { word: '自動販売機', reading: 'じどうはんばいき', romaji: 'jidouhanbaiki', meaning: 'Máy bán hàng tự động', type: 'Danh từ' },
    { word: '電話', reading: 'でんわ', romaji: 'denwa', meaning: 'Điện thoại', type: 'Danh từ' },
    { word: 'お国', reading: 'おくに', romaji: 'okuni', meaning: 'Đất nước (của bạn)', type: 'Danh từ' },
    { word: '会社', reading: 'かいしゃ', romaji: 'kaisha', meaning: 'Công ty', type: 'Danh từ' },
    { word: 'うち', reading: 'うち', romaji: 'uchi', meaning: 'Nhà', type: 'Danh từ' },
    { word: '靴', reading: 'くつ', romaji: 'kutsu', meaning: 'Giày', type: 'Danh từ' },
    { word: 'ネクタイ', reading: 'ネクタイ', romaji: 'nekutai', meaning: 'Cà vạt', type: 'Danh từ' },
    { word: '売り場', reading: 'うりば', romaji: 'uriba', meaning: 'Quầy bán hàng', type: 'Danh từ' },
    { word: '地下', reading: 'ちか', romaji: 'chika', meaning: 'Tầng hầm', type: 'Danh từ' },
    { word: '～円', reading: '～えん', romaji: '~en', meaning: 'Yên (tiền Nhật)', type: 'Hậu tố' },
    { word: 'いくら', reading: 'いくら', romaji: 'ikura', meaning: 'Bao nhiêu tiền', type: 'Từ để hỏi' },
    { word: '百', reading: 'ひゃく', romaji: 'hyaku', meaning: 'Trăm', type: 'Số đếm' },
    { word: '千', reading: 'せん', romaji: 'sen', meaning: 'Nghìn', type: 'Số đếm' },
    { word: '万', reading: 'まん', romaji: 'man', meaning: 'Mười nghìn', type: 'Số đếm' }
  ],
  4: [
    { word: '起きる', reading: 'おきる', romaji: 'okiru', meaning: 'Thức dậy', type: 'Động từ' },
    { word: '寝る', reading: 'ねる', romaji: 'neru', meaning: 'Ngủ', type: 'Động từ' },
    { word: '働く', reading: 'はたらく', romaji: 'hataraku', meaning: 'Làm việc', type: 'Động từ' },
    { word: '休む', reading: 'やすむ', romaji: 'yasumu', meaning: 'Nghỉ ngơi', type: 'Động từ' },
    { word: '勉強する', reading: 'べんきょうする', romaji: 'benkyousuru', meaning: 'Học', type: 'Động từ' },
    { word: '終わる', reading: 'おわる', romaji: 'owaru', meaning: 'Kết thúc', type: 'Động từ' },
    { word: 'デパート', reading: 'デパート', romaji: 'depaato', meaning: 'Cửa hàng bách hóa', type: 'Danh từ' },
    { word: '銀行', reading: 'ぎんこう', romaji: 'ginkou', meaning: 'Ngân hàng', type: 'Danh từ' },
    { word: '郵便局', reading: 'ゆうびんきょく', romaji: 'yuubinkyoku', meaning: 'Bưu điện', type: 'Danh từ' },
    { word: '図書館', reading: 'としょかん', romaji: 'toshokan', meaning: 'Thư viện', type: 'Danh từ' },
    { word: '美術館', reading: 'びじゅつかん', romaji: 'bijutsukan', meaning: 'Bảo tàng mỹ thuật', type: 'Danh từ' },
    { word: '今', reading: 'いま', romaji: 'ima', meaning: 'Bây giờ', type: 'Danh từ' },
    { word: '～時', reading: '～じ', romaji: '~ji', meaning: 'Giờ', type: 'Hậu tố' },
    { word: '～分', reading: '～ふん', romaji: '~fun', meaning: 'Phút', type: 'Hậu tố' },
    { word: '半', reading: 'はん', romaji: 'han', meaning: 'Rưỡi', type: 'Danh từ' },
    { word: '何時', reading: 'なんじ', romaji: 'nanji', meaning: 'Mấy giờ', type: 'Từ để hỏi' },
    { word: '何分', reading: 'なんぷん', romaji: 'nanpun', meaning: 'Mấy phút', type: 'Từ để hỏi' },
    { word: '午前', reading: 'ごぜん', romaji: 'gozen', meaning: 'Sáng (AM)', type: 'Danh từ' },
    { word: '午後', reading: 'ごご', romaji: 'gogo', meaning: 'Chiều (PM)', type: 'Danh từ' },
    { word: '朝', reading: 'あさ', romaji: 'asa', meaning: 'Buổi sáng', type: 'Danh từ' },
    { word: '昼', reading: 'ひる', romaji: 'hiru', meaning: 'Buổi trưa', type: 'Danh từ' },
    { word: '晩（夜）', reading: 'ばん（よる）', romaji: 'ban (yoru)', meaning: 'Buổi tối (đêm)', type: 'Danh từ' },
    { word: 'おととい', reading: 'おととい', romaji: 'ototoi', meaning: 'Hôm kia', type: 'Danh từ' },
    { word: 'きのう', reading: 'きのう', romaji: 'kinou', meaning: 'Hôm qua', type: 'Danh từ' },
    { word: 'きょう', reading: 'きょう', romaji: 'kyou', meaning: 'Hôm nay', type: 'Danh từ' },
    { word: 'あした', reading: 'あした', romaji: 'ashita', meaning: 'Ngày mai', type: 'Danh từ' },
    { word: 'あさって', reading: 'あさって', romaji: 'asatte', meaning: 'Ngày kia', type: 'Danh từ' },
    { word: 'けさ', reading: 'けさ', romaji: 'kesa', meaning: 'Sáng nay', type: 'Danh từ' },
    { word: '今晩', reading: 'こんばん', romaji: 'konban', meaning: 'Tối nay', type: 'Danh từ' },
    { word: '休み', reading: 'やすみ', romaji: 'yasumi', meaning: 'Ngày nghỉ', type: 'Danh từ' },
    { word: '昼休み', reading: 'ひるやすみ', romaji: 'hiruyasumi', meaning: 'Nghỉ trưa', type: 'Danh từ' },
    { word: '毎朝', reading: 'まいあさ', romaji: 'maiasa', meaning: 'Mỗi sáng', type: 'Danh từ' },
    { word: '毎晩', reading: 'まいばん', romaji: 'maiban', meaning: 'Mỗi tối', type: 'Danh từ' },
    { word: '毎日', reading: 'まいにち', romaji: 'mainichi', meaning: 'Mỗi ngày', type: 'Danh từ' },
    { word: '月曜日', reading: 'げつようび', romaji: 'getsuyoubi', meaning: 'Thứ hai', type: 'Danh từ' },
    { word: '火曜日', reading: 'かようび', romaji: 'kayoubi', meaning: 'Thứ ba', type: 'Danh từ' },
    { word: '水曜日', reading: 'すいようび', romaji: 'suiyoubi', meaning: 'Thứ tư', type: 'Danh từ' },
    { word: '木曜日', reading: 'もくようび', romaji: 'mokuyoubi', meaning: 'Thứ năm', type: 'Danh từ' },
    { word: '金曜日', reading: 'きんようび', romaji: 'kinyoubi', meaning: 'Thứ sáu', type: 'Danh từ' },
    { word: '土曜日', reading: 'どようび', romaji: 'doyoubi', meaning: 'Thứ bảy', type: 'Danh từ' },
    { word: '日曜日', reading: 'にちようび', romaji: 'nichiyoubi', meaning: 'Chủ nhật', type: 'Danh từ' },
    { word: '何曜日', reading: 'なんようび', romaji: 'nanyoubi', meaning: 'Thứ mấy', type: 'Từ để hỏi' },
    { word: '番号', reading: 'ばんごう', romaji: 'bangou', meaning: 'Số', type: 'Danh từ' },
    { word: '何番', reading: 'なんばん', romaji: 'nanban', meaning: 'Số mấy', type: 'Từ để hỏi' },
    { word: '～から', reading: '～から', romaji: '~kara', meaning: 'Từ ~', type: 'Trợ từ' },
    { word: '～まで', reading: '～まで', romaji: '~made', meaning: 'Đến ~', type: 'Trợ từ' },
    { word: '～と～', reading: '～と～', romaji: '~to~', meaning: '~ và ~', type: 'Trợ từ' },
    { word: 'そちら', reading: 'そちら', romaji: 'sochira', meaning: 'Phía bạn', type: 'Đại từ' },
    { word: '大変ですね', reading: 'たいへんですね', romaji: 'taihen desu ne', meaning: 'Vất vả quá nhỉ', type: 'Mẫu câu' }
  ],
  5: [
    { word: '行く', reading: 'いく', romaji: 'iku', meaning: 'Đi', type: 'Động từ' },
    { word: '来る', reading: 'くる', romaji: 'kuru', meaning: 'Đến', type: 'Động từ' },
    { word: '帰る', reading: 'かえる', romaji: 'kaeru', meaning: 'Về', type: 'Động từ' },
    { word: '学校', reading: 'がっこう', romaji: 'gakkou', meaning: 'Trường học', type: 'Danh từ' },
    { word: 'スーパー', reading: 'スーパー', romaji: 'suupaa', meaning: 'Siêu thị', type: 'Danh từ' },
    { word: '駅', reading: 'えき', romaji: 'eki', meaning: 'Nhà ga', type: 'Danh từ' },
    { word: '飛行機', reading: 'ひこうき', romaji: 'hikouki', meaning: 'Máy bay', type: 'Danh từ' },
    { word: '船', reading: 'ふね', romaji: 'fune', meaning: 'Tàu thủy', type: 'Danh từ' },
    { word: '電車', reading: 'でんしゃ', romaji: 'densha', meaning: 'Tàu điện', type: 'Danh từ' },
    { word: '地下鉄', reading: 'ちかてつ', romaji: 'chikatetsu', meaning: 'Tàu điện ngầm', type: 'Danh từ' },
    { word: '新幹線', reading: 'しんかんせん', romaji: 'shinkansen', meaning: 'Tàu siêu tốc', type: 'Danh từ' },
    { word: 'バス', reading: 'バス', romaji: 'basu', meaning: 'Xe buýt', type: 'Danh từ' },
    { word: 'タクシー', reading: 'タクシー', romaji: 'takushii', meaning: 'Taxi', type: 'Danh từ' },
    { word: '自転車', reading: 'じてんしゃ', romaji: 'jitensha', meaning: 'Xe đạp', type: 'Danh từ' },
    { word: '歩いて', reading: 'あるいて', romaji: 'aruite', meaning: 'Đi bộ', type: 'Trạng từ' },
    { word: '人', reading: 'ひと', romaji: 'hito', meaning: 'Người', type: 'Danh từ' },
    { word: '友達', reading: 'ともだち', romaji: 'tomodachi', meaning: 'Bạn bè', type: 'Danh từ' },
    { word: '彼', reading: 'かれ', romaji: 'kare', meaning: 'Anh ấy / Bạn trai', type: 'Danh từ' },
    { word: '彼女', reading: 'かのじょ', romaji: 'kanojo', meaning: 'Cô ấy / Bạn gái', type: 'Danh từ' },
    { word: '家族', reading: 'かぞく', romaji: 'kazoku', meaning: 'Gia đình', type: 'Danh từ' },
    { word: '一人で', reading: 'ひとりで', romaji: 'hitori de', meaning: 'Một mình', type: 'Trạng từ' },
    { word: '先週', reading: 'せんしゅう', romaji: 'senshuu', meaning: 'Tuần trước', type: 'Danh từ' },
    { word: '今週', reading: 'こんしゅう', romaji: 'konshuu', meaning: 'Tuần này', type: 'Danh từ' },
    { word: '来週', reading: 'らいしゅう', romaji: 'raishuu', meaning: 'Tuần sau', type: 'Danh từ' },
    { word: '先月', reading: 'せんげつ', romaji: 'sengetsu', meaning: 'Tháng trước', type: 'Danh từ' },
    { word: '今月', reading: 'こんげつ', romaji: 'kongetsu', meaning: 'Tháng này', type: 'Danh từ' },
    { word: '来月', reading: 'らいげつ', romaji: 'raigetsu', meaning: 'Tháng sau', type: 'Danh từ' },
    { word: '去年', reading: 'きょねん', romaji: 'kyonen', meaning: 'Năm ngoái', type: 'Danh từ' },
    { word: '今年', reading: 'ことし', romaji: 'kotoshi', meaning: 'Năm nay', type: 'Danh từ' },
    { word: '来年', reading: 'らいねん', romaji: 'rainen', meaning: 'Năm sau', type: 'Danh từ' },
    { word: '～月', reading: '～がつ', romaji: '~gatsu', meaning: 'Tháng ~', type: 'Hậu tố' },
    { word: '何月', reading: 'なんがつ', romaji: 'nangatsu', meaning: 'Tháng mấy', type: 'Từ để hỏi' },
    { word: '１日', reading: 'ついたち', romaji: 'tsuitachi', meaning: 'Ngày mùng 1', type: 'Danh từ' },
    { word: '２日', reading: 'ふつか', romaji: 'futsuka', meaning: 'Ngày mùng 2', type: 'Danh từ' },
    { word: '３日', reading: 'みっか', romaji: 'mikka', meaning: 'Ngày mùng 3', type: 'Danh từ' },
    { word: '４日', reading: 'よっか', romaji: 'yokka', meaning: 'Ngày mùng 4', type: 'Danh từ' },
    { word: '５日', reading: 'いつか', romaji: 'itsuka', meaning: 'Ngày mùng 5', type: 'Danh từ' },
    { word: '６日', reading: 'むいか', romaji: 'muika', meaning: 'Ngày mùng 6', type: 'Danh từ' },
    { word: '７日', reading: 'なのか', romaji: 'nanoka', meaning: 'Ngày mùng 7', type: 'Danh từ' },
    { word: '８日', reading: 'ようか', romaji: 'youka', meaning: 'Ngày mùng 8', type: 'Danh từ' },
    { word: '９日', reading: 'ここのか', romaji: 'kokonoka', meaning: 'Ngày mùng 9', type: 'Danh từ' },
    { word: '１０日', reading: 'とおか', romaji: 'tooka', meaning: 'Ngày mùng 10', type: 'Danh từ' },
    { word: '１４日', reading: 'じゅうよっか', romaji: 'juuyokka', meaning: 'Ngày 14', type: 'Danh từ' },
    { word: '２０日', reading: 'はつか', romaji: 'hatsuka', meaning: 'Ngày 20', type: 'Danh từ' },
    { word: '２４日', reading: 'にじゅうよっか', romaji: 'nijuuyokka', meaning: 'Ngày 24', type: 'Danh từ' },
    { word: '～日', reading: '～にち', romaji: '~nichi', meaning: 'Ngày ~', type: 'Hậu tố' },
    { word: '何日', reading: 'なんにち', romaji: 'nannichi', meaning: 'Ngày mấy', type: 'Từ để hỏi' },
    { word: 'いつ', reading: 'いつ', romaji: 'itsu', meaning: 'Khi nào', type: 'Từ để hỏi' },
    { word: '誕生日', reading: 'たんじょうび', romaji: 'tanjoubi', meaning: 'Sinh nhật', type: 'Danh từ' },
    { word: '普通', reading: 'ふつう', romaji: 'futsuu', meaning: 'Tàu thường', type: 'Danh từ' },
    { word: '急行', reading: 'きゅうこう', romaji: 'kyuukou', meaning: 'Tàu tốc hành', type: 'Danh từ' },
    { word: '特急', reading: 'とっきゅう', romaji: 'tokkyuu', meaning: 'Tàu tốc hành đặc biệt', type: 'Danh từ' },
    { word: '次の', reading: 'つぎの', romaji: 'tsugino', meaning: 'Tiếp theo', type: 'Danh từ' },
    { word: 'どういたしまして', reading: 'どういたしまして', romaji: 'douitashimashite', meaning: 'Không có chi', type: 'Mẫu câu' }
  ],
  6: [
    { word: '食べる', reading: 'たべる', romaji: 'taberu', meaning: 'Ăn', type: 'Động từ' },
    { word: '飲む', reading: 'のむ', romaji: 'nomu', meaning: 'Uống', type: 'Động từ' },
    { word: '吸う', reading: 'すう', romaji: 'suu', meaning: 'Hút (thuốc)', type: 'Động từ' },
    { word: '見る', reading: 'みる', romaji: 'miru', meaning: 'Xem, nhìn', type: 'Động từ' },
    { word: '聞く', reading: 'きく', romaji: 'kiku', meaning: 'Nghe', type: 'Động từ' },
    { word: '読む', reading: 'よむ', romaji: 'yomu', meaning: 'Đọc', type: 'Động từ' },
    { word: '書く', reading: 'かく', romaji: 'kaku', meaning: 'Viết, vẽ', type: 'Động từ' },
    { word: '買う', reading: 'かう', romaji: 'kau', meaning: 'Mua', type: 'Động từ' },
    { word: '撮る', reading: 'とる', romaji: 'toru', meaning: 'Chụp (ảnh)', type: 'Động từ' },
    { word: 'する', reading: 'する', romaji: 'suru', meaning: 'Làm, chơi', type: 'Động từ' },
    { word: '会う', reading: 'あう', romaji: 'au', meaning: 'Gặp', type: 'Động từ' },
    { word: 'ごはん', reading: 'ごはん', romaji: 'gohan', meaning: 'Cơm, bữa ăn', type: 'Danh từ' },
    { word: '朝ごはん', reading: 'あさごはん', romaji: 'asagohan', meaning: 'Bữa sáng', type: 'Danh từ' },
    { word: '昼ごはん', reading: 'ひるごはん', romaji: 'hirugohan', meaning: 'Bữa trưa', type: 'Danh từ' },
    { word: '晩ごはん', reading: 'ばんごはん', romaji: 'bangohan', meaning: 'Bữa tối', type: 'Danh từ' },
    { word: 'パン', reading: 'パン', romaji: 'pan', meaning: 'Bánh mì', type: 'Danh từ' },
    { word: '卵', reading: 'たまご', romaji: 'tamago', meaning: 'Trứng', type: 'Danh từ' },
    { word: '肉', reading: 'にく', romaji: 'niku', meaning: 'Thịt', type: 'Danh từ' },
    { word: '魚', reading: 'さかな', romaji: 'sakana', meaning: 'Cá', type: 'Danh từ' },
    { word: '野菜', reading: 'やさい', romaji: 'yasai', meaning: 'Rau', type: 'Danh từ' },
    { word: '果物', reading: 'くだもの', romaji: 'kudamono', meaning: 'Trái cây', type: 'Danh từ' },
    { word: '水', reading: 'みず', romaji: 'mizu', meaning: 'Nước', type: 'Danh từ' },
    { word: 'お茶', reading: 'おちゃ', romaji: 'ocha', meaning: 'Trà', type: 'Danh từ' },
    { word: '紅茶', reading: 'こうちゃ', romaji: 'koucha', meaning: 'Hồng trà', type: 'Danh từ' },
    { word: '牛乳', reading: 'ぎゅうにゅう', romaji: 'gyuunyuu', meaning: 'Sữa bò', type: 'Danh từ' },
    { word: 'ジュース', reading: 'ジュース', romaji: 'juusu', meaning: 'Nước trái cây', type: 'Danh từ' },
    { word: 'ビール', reading: 'ビール', romaji: 'biiru', meaning: 'Bia', type: 'Danh từ' },
    { word: 'お酒', reading: 'おさけ', romaji: 'osake', meaning: 'Rượu', type: 'Danh từ' },
    { word: 'ビデオ', reading: 'ビデオ', romaji: 'bideo', meaning: 'Video', type: 'Danh từ' },
    { word: '映画', reading: 'えいが', romaji: 'eiga', meaning: 'Phim', type: 'Danh từ' },
    { word: '手紙', reading: 'てがみ', romaji: 'tegami', meaning: 'Thư', type: 'Danh từ' },
    { word: 'レポート', reading: 'レポート', romaji: 'repooto', meaning: 'Báo cáo', type: 'Danh từ' },
    { word: '写真', reading: 'しゃしん', romaji: 'shashin', meaning: 'Ảnh', type: 'Danh từ' },
    { word: '店', reading: 'みせ', romaji: 'mise', meaning: 'Cửa hàng', type: 'Danh từ' },
    { word: '庭', reading: 'にわ', romaji: 'niwa', meaning: 'Sân, vườn', type: 'Danh từ' },
    { word: '宿題', reading: 'しゅくだい', romaji: 'shukudai', meaning: 'Bài tập về nhà', type: 'Danh từ' },
    { word: 'テニス', reading: 'テニス', romaji: 'tenisu', meaning: 'Quần vợt', type: 'Danh từ' },
    { word: 'サッカー', reading: 'サッカー', romaji: 'sakkaa', meaning: 'Bóng đá', type: 'Danh từ' },
    { word: 'お花見', reading: 'おはなみ', romaji: 'ohanami', meaning: 'Ngắm hoa anh đào', type: 'Danh từ' },
    { word: '何', reading: 'なに', romaji: 'nani', meaning: 'Cái gì', type: 'Từ để hỏi' },
    { word: 'いっしょに', reading: 'いっしょに', romaji: 'isshoni', meaning: 'Cùng nhau', type: 'Phó từ' },
    { word: 'ちょっと', reading: 'ちょっと', romaji: 'chotto', meaning: 'Một chút', type: 'Phó từ' },
    { word: 'いつも', reading: 'いつも', romaji: 'itsumo', meaning: 'Luôn luôn', type: 'Phó từ' },
    { word: '時々', reading: 'ときどき', romaji: 'tokidoki', meaning: 'Thỉnh thoảng', type: 'Phó từ' },
    { word: 'それから', reading: 'それから', romaji: 'sorekara', meaning: 'Sau đó', type: 'Liên từ' },
    { word: 'ええ', reading: 'ええ', romaji: 'ee', meaning: 'Vâng / Ừ', type: 'Cảm thán' },
    { word: 'いいですね', reading: 'いいですね', romaji: 'iidesune', meaning: 'Được đấy nhỉ', type: 'Mẫu câu' },
    { word: 'わかりました', reading: 'わかりました', romaji: 'wakarimashita', meaning: 'Tôi hiểu rồi', type: 'Mẫu câu' },
    { word: '何ですか', reading: 'なんですか', romaji: 'nandesuka', meaning: 'Có chuyện gì vậy?', type: 'Mẫu câu' }
  ],
  7: [
    { word: '切る', reading: 'きる', romaji: 'kiru', meaning: 'Cắt', type: 'Động từ' },
    { word: '送る', reading: 'おくる', romaji: 'okuru', meaning: 'Gửi', type: 'Động từ' },
    { word: 'あげる', reading: 'あげる', romaji: 'ageru', meaning: 'Cho, tặng', type: 'Động từ' },
    { word: 'もらう', reading: 'もらう', romaji: 'morau', meaning: 'Nhận', type: 'Động từ' },
    { word: '貸す', reading: 'かす', romaji: 'kasu', meaning: 'Cho mượn', type: 'Động từ' },
    { word: '借りる', reading: 'かりる', romaji: 'kariru', meaning: 'Mượn', type: 'Động từ' },
    { word: '教える', reading: 'おしえる', romaji: 'oshieru', meaning: 'Dạy', type: 'Động từ' },
    { word: '習う', reading: 'ならう', romaji: 'narau', meaning: 'Học', type: 'Động từ' },
    { word: 'かける', reading: 'かける', romaji: 'kakeru', meaning: 'Gọi (điện thoại)', type: 'Động từ' },
    { word: '手', reading: 'て', romaji: 'te', meaning: 'Tay', type: 'Danh từ' },
    { word: 'はし', reading: 'はし', romaji: 'hashi', meaning: 'Đũa', type: 'Danh từ' },
    { word: 'スプーン', reading: 'スプーン', romaji: 'supuun', meaning: 'Thìa', type: 'Danh từ' },
    { word: 'ナイフ', reading: 'ナイフ', romaji: 'naifu', meaning: 'Dao', type: 'Danh từ' },
    { word: 'フォーク', reading: 'フォーク', romaji: 'fooku', meaning: 'Nĩa', type: 'Danh từ' },
    { word: 'はさみ', reading: 'はさみ', romaji: 'hasami', meaning: 'Kéo', type: 'Danh từ' },
    { word: 'ファクス', reading: 'ファクス', romaji: 'fakusu', meaning: 'Fax', type: 'Danh từ' },
    { word: 'ワープロ', reading: 'ワープロ', romaji: 'waapuro', meaning: 'Máy đánh chữ', type: 'Danh từ' },
    { word: 'パソコン', reading: 'パソコン', romaji: 'pasokon', meaning: 'Máy tính cá nhân', type: 'Danh từ' },
    { word: 'パンチ', reading: 'パンチ', romaji: 'panchi', meaning: 'Đồ dập lỗ', type: 'Danh từ' },
    { word: 'ホッチキス', reading: 'ホッチキス', romaji: 'hotchikisu', meaning: 'Cái dập ghim', type: 'Danh từ' },
    { word: 'セロテープ', reading: 'セロテープ', romaji: 'seroteepu', meaning: 'Băng dính', type: 'Danh từ' },
    { word: '消しゴム', reading: 'けしゴム', romaji: 'keshigomu', meaning: 'Cục tẩy', type: 'Danh từ' },
    { word: '紙', reading: 'かみ', romaji: 'kami', meaning: 'Giấy', type: 'Danh từ' },
    { word: '花', reading: 'はな', romaji: 'hana', meaning: 'Hoa', type: 'Danh từ' },
    { word: 'シャツ', reading: 'シャツ', romaji: 'shatsu', meaning: 'Áo sơ mi', type: 'Danh từ' },
    { word: 'プレゼント', reading: 'プレゼント', romaji: 'purezento', meaning: 'Quà tặng', type: 'Danh từ' },
    { word: '荷物', reading: 'にもつ', romaji: 'nimotsu', meaning: 'Hành lý', type: 'Danh từ' },
    { word: 'お金', reading: 'おかね', romaji: 'okane', meaning: 'Tiền', type: 'Danh từ' },
    { word: '切符', reading: 'きっぷ', romaji: 'kippu', meaning: 'Vé', type: 'Danh từ' },
    { word: 'クリスマス', reading: 'クリスマス', romaji: 'kurisumasu', meaning: 'Giáng sinh', type: 'Danh từ' },
    { word: '父', reading: 'ちち', romaji: 'chichi', meaning: 'Bố (mình)', type: 'Danh từ' },
    { word: '母', reading: 'はは', romaji: 'haha', meaning: 'Mẹ (mình)', type: 'Danh từ' },
    { word: 'お父さん', reading: 'おとうさん', romaji: 'otousan', meaning: 'Bố (người khác)', type: 'Danh từ' },
    { word: 'お母さん', reading: 'おかあさん', romaji: 'okaasan', meaning: 'Mẹ (người khác)', type: 'Danh từ' },
    { word: 'もう', reading: 'もう', romaji: 'mou', meaning: 'Đã', type: 'Phó từ' },
    { word: 'まだ', reading: 'まだ', romaji: 'mada', meaning: 'Chưa', type: 'Phó từ' },
    { word: 'これから', reading: 'これから', romaji: 'korekara', meaning: 'Từ bây giờ', type: 'Phó từ' },
    { word: 'すてきですね', reading: 'すてきですね', romaji: 'sutekidesune', meaning: 'Tuyệt nhỉ', type: 'Mẫu câu' },
    { word: 'ごめんください', reading: 'ごめんください', romaji: 'gomen kudasai', meaning: 'Xin lỗi, có ai ở nhà không', type: 'Mẫu câu' },
    { word: 'いらっしゃい', reading: 'いらっしゃい', romaji: 'irasshai', meaning: 'Chào mừng (bạn đến chơi)', type: 'Mẫu câu' },
    { word: 'どうぞお上がりください', reading: 'どうぞおあがりください', romaji: 'douzo oagari kudasai', meaning: 'Xin mời vào', type: 'Mẫu câu' },
    { word: '失礼します', reading: 'しつれいします', romaji: 'shitsureishimasu', meaning: 'Xin thất lễ', type: 'Mẫu câu' },
    { word: '～はいかがですか', reading: '～はいかがですか', romaji: '~wa ikagadesuka', meaning: 'Bạn có dùng ~ không?', type: 'Mẫu câu' },
    { word: 'いただきます', reading: 'いただきます', romaji: 'itadakimasu', meaning: 'Mời dùng bữa (nói trước khi ăn)', type: 'Mẫu câu' },
    { word: 'ごちそうさま[でした]', reading: 'ごちそうさま[でした]', romaji: 'gochisousama[deshita]', meaning: 'Cảm ơn vì bữa ăn ngon', type: 'Mẫu câu' }
  ],
  8: [
    { word: 'ハンサム[な]', reading: 'ハンサム[な]', romaji: 'hansamu[na]', meaning: 'Đẹp trai', type: 'Tính từ な' },
    { word: 'きれい[な]', reading: 'きれい[な]', romaji: 'kirei[na]', meaning: 'Đẹp, sạch sẽ', type: 'Tính từ な' },
    { word: '静か[な]', reading: 'しずか[な]', romaji: 'shizuka[na]', meaning: 'Yên tĩnh', type: 'Tính từ な' },
    { word: 'にぎやか[な]', reading: 'にぎやか[な]', romaji: 'nigiyaka[na]', meaning: 'Nhộn nhịp', type: 'Tính từ な' },
    { word: '有名[な]', reading: 'ゆうめい[な]', romaji: 'yuumei[na]', meaning: 'Nổi tiếng', type: 'Tính từ な' },
    { word: '親切[な]', reading: 'しんせつ[な]', romaji: 'shinsetsu[na]', meaning: 'Tốt bụng', type: 'Tính từ な' },
    { word: '元気[な]', reading: 'げんき[な]', romaji: 'genki[na]', meaning: 'Khỏe mạnh', type: 'Tính từ な' },
    { word: '暇[な]', reading: 'ひま[な]', romaji: 'hima[na]', meaning: 'Rảnh rỗi', type: 'Tính từ な' },
    { word: '便利[な]', reading: 'べんり[な]', romaji: 'benri[na]', meaning: 'Tiện lợi', type: 'Tính từ な' },
    { word: 'すてき[な]', reading: 'すてき[な]', romaji: 'suteki[na]', meaning: 'Tuyệt vời', type: 'Tính từ な' },
    { word: '大きい', reading: 'おおきい', romaji: 'ookii', meaning: 'To, lớn', type: 'Tính từ い' },
    { word: '小さい', reading: 'ちいさい', romaji: 'chiisai', meaning: 'Nhỏ, bé', type: 'Tính từ い' },
    { word: '新しい', reading: 'あたらしい', romaji: 'atarashii', meaning: 'Mới', type: 'Tính từ い' },
    { word: '古い', reading: 'ふるい', romaji: 'furui', meaning: 'Cũ', type: 'Tính từ い' },
    { word: 'いい（よい）', reading: 'いい（よい）', romaji: 'ii (yoi)', meaning: 'Tốt', type: 'Tính từ い' },
    { word: '悪い', reading: 'わるい', romaji: 'warui', meaning: 'Xấu', type: 'Tính từ い' },
    { word: '暑い', reading: 'あつい', romaji: 'atsui', meaning: 'Nóng', type: 'Tính từ い' },
    { word: '熱い', reading: 'あつい', romaji: 'atsui', meaning: 'Nóng (đồ vật)', type: 'Tính từ い' },
    { word: '寒い', reading: 'さむい', romaji: 'samui', meaning: 'Lạnh (thời tiết)', type: 'Tính từ い' },
    { word: '冷たい', reading: 'つめたい', romaji: 'tsumetai', meaning: 'Lạnh (đồ vật)', type: 'Tính từ い' },
    { word: '難しい', reading: 'むずかしい', romaji: 'muzukashii', meaning: 'Khó', type: 'Tính từ い' },
    { word: '易しい', reading: 'やさしい', romaji: 'yasashii', meaning: 'Dễ', type: 'Tính từ い' },
    { word: '高い', reading: 'たかい', romaji: 'takai', meaning: 'Đắt, cao', type: 'Tính từ い' },
    { word: '安い', reading: 'やすい', romaji: 'yasui', meaning: 'Rẻ', type: 'Tính từ い' },
    { word: '低い', reading: 'ひくい', romaji: 'hikui', meaning: 'Thấp', type: 'Tính từ い' },
    { word: 'おもしろい', reading: 'おもしろい', romaji: 'omoshiroi', meaning: 'Thú vị', type: 'Tính từ い' },
    { word: 'おいしい', reading: 'おいしい', romaji: 'oishii', meaning: 'Ngon', type: 'Tính từ い' },
    { word: '忙しい', reading: 'いそがしい', romaji: 'isogashii', meaning: 'Bận rộn', type: 'Tính từ い' },
    { word: '楽しい', reading: 'たのしい', romaji: 'tanoshii', meaning: 'Vui', type: 'Tính từ い' },
    { word: '白い', reading: 'しろい', romaji: 'shiroi', meaning: 'Trắng', type: 'Tính từ い' },
    { word: '黒い', reading: 'くろい', romaji: 'kuroi', meaning: 'Đen', type: 'Tính từ い' },
    { word: '赤い', reading: 'あかい', romaji: 'akai', meaning: 'Đỏ', type: 'Tính từ い' },
    { word: '青い', reading: 'あおい', romaji: 'aoi', meaning: 'Xanh da trời', type: 'Tính từ い' },
    { word: '桜', reading: 'さくら', romaji: 'sakura', meaning: 'Hoa anh đào', type: 'Danh từ' },
    { word: '山', reading: 'やま', romaji: 'yama', meaning: 'Núi', type: 'Danh từ' },
    { word: '町', reading: 'まち', romaji: 'machi', meaning: 'Thành phố, thị trấn', type: 'Danh từ' },
    { word: '食べ物', reading: 'たべもの', romaji: 'tabemono', meaning: 'Đồ ăn', type: 'Danh từ' },
    { word: '車', reading: 'くるま', romaji: 'kuruma', meaning: 'Ô tô', type: 'Danh từ' },
    { word: '所', reading: 'ところ', romaji: 'tokoro', meaning: 'Nơi, chỗ', type: 'Danh từ' },
    { word: '寮', reading: 'りょう', romaji: 'ryou', meaning: 'Ký túc xá', type: 'Danh từ' },
    { word: '勉強', reading: 'べんきょう', romaji: 'benkyou', meaning: 'Việc học', type: 'Danh từ' },
    { word: '生活', reading: 'せいかつ', romaji: 'seikatsu', meaning: 'Cuộc sống', type: 'Danh từ' },
    { word: 'お仕事', reading: 'おしごと', romaji: 'oshigoto', meaning: 'Công việc', type: 'Danh từ' },
    { word: 'どう', reading: 'どう', romaji: 'dou', meaning: 'Thế nào', type: 'Từ để hỏi' },
    { word: 'どんな～', reading: 'どんな～', romaji: 'donna~', meaning: '~ như thế nào', type: 'Từ để hỏi' },
    { word: 'どれ', reading: 'どれ', romaji: 'dore', meaning: 'Cái nào', type: 'Từ để hỏi' },
    { word: 'とても', reading: 'とても', romaji: 'totemo', meaning: 'Rất', type: 'Phó từ' },
    { word: 'あまり', reading: 'あまり', romaji: 'amari', meaning: 'Không... lắm', type: 'Phó từ' },
    { word: 'そして', reading: 'そして', romaji: 'soshite', meaning: 'Và', type: 'Liên từ' },
    { word: '～が、～', reading: '～が、～', romaji: '~ga, ~', meaning: '~ nhưng ~', type: 'Liên từ' },
    { word: 'お元気ですか', reading: 'おげんきですか', romaji: 'ogenki desu ka', meaning: 'Bạn có khỏe không?', type: 'Mẫu câu' },
    { word: 'そうですね', reading: 'そうですね', romaji: 'sou desu ne', meaning: 'À, ừ nhỉ', type: 'Mẫu câu' },
    { word: '日本の生活に慣れましたか', reading: 'にほんのせいかつになれましたか', romaji: 'Nihon no seikatsu ni naremashita ka', meaning: 'Bạn quen với cuộc sống ở Nhật chưa?', type: 'Mẫu câu' },
    { word: '～、もう一杯いかがですか', reading: '～、もういっぱいいかがですか', romaji: '~, mou ippai ikaga desu ka', meaning: 'Dùng thêm một cốc ~ nữa nhé?', type: 'Mẫu câu' },
    { word: 'いいえ、けっこうです', reading: 'いいえ、けっこうです', romaji: 'iie, kekkou desu', meaning: 'Không, đủ rồi', type: 'Mẫu câu' },
    { word: 'もう～です[ね]', reading: 'もう～です[ね]', romaji: 'mou~ desu[ne]', meaning: 'Đã ~ rồi nhỉ', type: 'Mẫu câu' },
    { word: 'そろそろ失礼します', reading: 'そろそろしつれいします', romaji: 'sorosoro shitsurei shimasu', meaning: 'Đến lúc tôi phải xin phép về', type: 'Mẫu câu' },
    { word: 'またいらっしゃってください', reading: 'またいらっしゃってください', romaji: 'mata irasshatte kudasai', meaning: 'Lần sau lại đến chơi nhé', type: 'Mẫu câu' }
  ],
  9: [
    { word: '分かる', reading: 'わかる', romaji: 'wakaru', meaning: 'Hiểu', type: 'Động từ' },
    { word: 'ある', reading: 'ある', romaji: 'aru', meaning: 'Có', type: 'Động từ' },
    { word: '好き[な]', reading: 'すき[な]', romaji: 'suki[na]', meaning: 'Thích', type: 'Tính từ な' },
    { word: '嫌い[な]', reading: 'きらい[な]', romaji: 'kirai[na]', meaning: 'Ghét', type: 'Tính từ な' },
    { word: '上手[な]', reading: 'じょうず[な]', romaji: 'jouzu[na]', meaning: 'Giỏi', type: 'Tính từ な' },
    { word: '下手[な]', reading: 'へた[な]', romaji: 'heta[na]', meaning: 'Kém', type: 'Tính từ な' },
    { word: '料理', reading: 'りょうり', romaji: 'ryouri', meaning: 'Món ăn, nấu ăn', type: 'Danh từ' },
    { word: '飲み物', reading: 'のみもの', romaji: 'nomimono', meaning: 'Đồ uống', type: 'Danh từ' },
    { word: 'スポーツ', reading: 'スポーツ', romaji: 'supootsu', meaning: 'Thể thao', type: 'Danh từ' },
    { word: '野球', reading: 'やきゅう', romaji: 'yakyuu', meaning: 'Bóng chày', type: 'Danh từ' },
    { word: 'ダンス', reading: 'ダンス', romaji: 'dansu', meaning: 'Khiêu vũ', type: 'Danh từ' },
    { word: '音楽', reading: 'おんがく', romaji: 'ongaku', meaning: 'Âm nhạc', type: 'Danh từ' },
    { word: '歌', reading: 'うた', romaji: 'uta', meaning: 'Bài hát', type: 'Danh từ' },
    { word: 'クラシック', reading: 'クラシック', romaji: 'kurashikku', meaning: 'Nhạc cổ điển', type: 'Danh từ' },
    { word: 'ジャズ', reading: 'ジャズ', romaji: 'jazu', meaning: 'Nhạc jazz', type: 'Danh từ' },
    { word: 'コンサート', reading: 'コンサート', romaji: 'konsaato', meaning: 'Buổi hòa nhạc', type: 'Danh từ' },
    { word: 'カラオケ', reading: 'カラオケ', romaji: 'karaoke', meaning: 'Karaoke', type: 'Danh từ' },
    { word: '歌舞伎', reading: 'かぶき', romaji: 'kabuki', meaning: 'Kịch Kabuki', type: 'Danh từ' },
    { word: '絵', reading: 'え', romaji: 'e', meaning: 'Tranh', type: 'Danh từ' },
    { word: '字', reading: 'じ', romaji: 'ji', meaning: 'Chữ', type: 'Danh từ' },
    { word: '漢字', reading: 'かんじ', romaji: 'kanji', meaning: 'Chữ Hán', type: 'Danh từ' },
    { word: 'ひらがな', reading: 'ひらがな', romaji: 'hiragana', meaning: 'Chữ Hiragana', type: 'Danh từ' },
    { word: 'カタカナ', reading: 'カタカナ', romaji: 'katakana', meaning: 'Chữ Katakana', type: 'Danh từ' },
    { word: 'ローマ字', reading: 'ローマじ', romaji: 'roomaji', meaning: 'Chữ Romaji', type: 'Danh từ' },
    { word: '細かいお金', reading: 'こまかいおかね', romaji: 'komakai okane', meaning: 'Tiền lẻ', type: 'Danh từ' },
    { word: 'チケット', reading: 'チケット', romaji: 'chiketto', meaning: 'Vé', type: 'Danh từ' },
    { word: '時間', reading: 'じかん', romaji: 'jikan', meaning: 'Thời gian', type: 'Danh từ' },
    { word: '用事', reading: 'ようじ', romaji: 'youji', meaning: 'Việc bận', type: 'Danh từ' },
    { word: '約束', reading: 'やくそく', romaji: 'yakusoku', meaning: 'Cuộc hẹn', type: 'Danh từ' },
    { word: 'ご主人', reading: 'ごしゅじん', romaji: 'goshujin', meaning: 'Chồng (người khác)', type: 'Danh từ' },
    { word: '夫 / 主人', reading: 'おっと / しゅじん', romaji: 'otto / shujin', meaning: 'Chồng (mình)', type: 'Danh từ' },
    { word: '奥さん', reading: 'おくさん', romaji: 'okusan', meaning: 'Vợ (người khác)', type: 'Danh từ' },
    { word: '妻 / 家内', reading: 'つま / かない', romaji: 'tsuma / kanai', meaning: 'Vợ (mình)', type: 'Danh từ' },
    { word: '子ども', reading: 'こども', romaji: 'kodomo', meaning: 'Con cái', type: 'Danh từ' },
    { word: 'よく', reading: 'よく', romaji: 'yoku', meaning: 'Rõ, tốt', type: 'Phó từ' },
    { word: 'だいたい', reading: 'だいたい', romaji: 'daitai', meaning: 'Đại khái', type: 'Phó từ' },
    { word: 'たくさん', reading: 'たくさん', romaji: 'takusan', meaning: 'Nhiều', type: 'Phó từ' },
    { word: '少し', reading: 'すこし', romaji: 'sukoshi', meaning: 'Một ít', type: 'Phó từ' },
    { word: '全然', reading: 'ぜんぜん', romaji: 'zenzen', meaning: 'Hoàn toàn không', type: 'Phó từ' },
    { word: '早く/速く', reading: 'はやく', romaji: 'hayaku', meaning: 'Sớm, nhanh', type: 'Phó từ' },
    { word: '～から', reading: '～から', romaji: '~kara', meaning: 'Vì ~', type: 'Trợ từ' },
    { word: 'どうして', reading: 'どうして', romaji: 'doushite', meaning: 'Tại sao', type: 'Từ để hỏi' },
    { word: '残念です[ね]', reading: 'ざんねんです[ね]', romaji: 'zannen desu [ne]', meaning: 'Đáng tiếc nhỉ', type: 'Mẫu câu' },
    { word: 'すみません', reading: 'すみません', romaji: 'sumimasen', meaning: 'Xin lỗi', type: 'Mẫu câu' },
    { word: 'もしもし', reading: 'もしもし', romaji: 'moshimoshi', meaning: 'Alo', type: 'Mẫu câu' }
  ],
  10: [
    { word: 'あります', reading: 'あります', romaji: 'arimasu', meaning: 'Có (đồ vật, cây cối)', type: 'Động từ' },
    { word: 'います', reading: 'います', romaji: 'imasu', meaning: 'Có (người, động vật)', type: 'Động từ' },
    { word: 'いろいろ[な]', reading: 'いろいろ[な]', romaji: 'iroiro[na]', meaning: 'Nhiều loại', type: 'Tính từ な' },
    { word: '男の人', reading: 'おとこのひと', romaji: 'otoko no hito', meaning: 'Người đàn ông', type: 'Danh từ' },
    { word: '女の人', reading: 'おんなのひと', romaji: 'onna no hito', meaning: 'Người phụ nữ', type: 'Danh từ' },
    { word: '男の子', reading: 'おとこのこ', romaji: 'otoko no ko', meaning: 'Bé trai', type: 'Danh từ' },
    { word: '女の子', reading: 'おんなのこ', romaji: 'onna no ko', meaning: 'Bé gái', type: 'Danh từ' },
    { word: '犬', reading: 'いぬ', romaji: 'inu', meaning: 'Con chó', type: 'Danh từ' },
    { word: '猫', reading: 'ねこ', romaji: 'neko', meaning: 'Con mèo', type: 'Danh từ' },
    { word: '木', reading: 'き', romaji: 'ki', meaning: 'Cây', type: 'Danh từ' },
    { word: '物', reading: 'もの', romaji: 'mono', meaning: 'Đồ vật', type: 'Danh từ' },
    { word: 'フィルム', reading: 'フィルム', romaji: 'firumu', meaning: 'Cuộn phim', type: 'Danh từ' },
    { word: '電池', reading: 'でんち', romaji: 'denchi', meaning: 'Pin', type: 'Danh từ' },
    { word: '箱', reading: 'はこ', romaji: 'hako', meaning: 'Hộp', type: 'Danh từ' },
    { word: 'スイッチ', reading: 'スイッチ', romaji: 'suitchi', meaning: 'Công tắc', type: 'Danh từ' },
    { word: '冷蔵庫', reading: 'れいぞうこ', romaji: 'reizouko', meaning: 'Tủ lạnh', type: 'Danh từ' },
    { word: 'テーブル', reading: 'テーブル', romaji: 'teeburu', meaning: 'Bàn', type: 'Danh từ' },
    { word: 'ベッド', reading: 'ベッド', romaji: 'beddo', meaning: 'Giường', type: 'Danh từ' },
    { word: '棚', reading: 'たな', romaji: 'tana', meaning: 'Giá, kệ', type: 'Danh từ' },
    { word: 'ドア', reading: 'ドア', romaji: 'doa', meaning: 'Cửa ra vào', type: 'Danh từ' },
    { word: '窓', reading: 'まど', romaji: 'mado', meaning: 'Cửa sổ', type: 'Danh từ' },
    { word: 'ポスト', reading: 'ポスト', romaji: 'posuto', meaning: 'Hộp thư', type: 'Danh từ' },
    { word: 'ビル', reading: 'ビル', romaji: 'biru', meaning: 'Tòa nhà', type: 'Danh từ' },
    { word: '公園', reading: 'こうえん', romaji: 'kouen', meaning: 'Công viên', type: 'Danh từ' },
    { word: '喫茶店', reading: 'きっさてん', romaji: 'kissaten', meaning: 'Quán giải khát', type: 'Danh từ' },
    { word: '本屋', reading: 'ほんや', romaji: 'honya', meaning: 'Hiệu sách', type: 'Danh từ' },
    { word: '～屋', reading: '～や', romaji: '~ya', meaning: 'Cửa hàng ~', type: 'Hậu tố' },
    { word: '乗り場', reading: 'のりば', romaji: 'noriba', meaning: 'Điểm lên xe', type: 'Danh từ' },
    { word: '県', reading: 'けん', romaji: 'ken', meaning: 'Tỉnh', type: 'Danh từ' },
    { word: '上', reading: 'うえ', romaji: 'ue', meaning: 'Trên', type: 'Danh từ' },
    { word: '下', reading: 'した', romaji: 'shita', meaning: 'Dưới', type: 'Danh từ' },
    { word: '前', reading: 'まえ', romaji: 'mae', meaning: 'Trước', type: 'Danh từ' },
    { word: '後ろ', reading: 'うしろ', romaji: 'ushiro', meaning: 'Sau', type: 'Danh từ' },
    { word: '右', reading: 'みぎ', romaji: 'migi', meaning: 'Phải', type: 'Danh từ' },
    { word: '左', reading: 'ひだり', romaji: 'hidari', meaning: 'Trái', type: 'Danh từ' },
    { word: '中', reading: 'なか', romaji: 'naka', meaning: 'Trong', type: 'Danh từ' },
    { word: '外', reading: 'そと', romaji: 'soto', meaning: 'Ngoài', type: 'Danh từ' },
    { word: '隣', reading: 'となり', romaji: 'tonari', meaning: 'Bên cạnh', type: 'Danh từ' },
    { word: '近く', reading: 'ちかく', romaji: 'chikaku', meaning: 'Gần', type: 'Danh từ' },
    { word: '間', reading: 'あいだ', romaji: 'aida', meaning: 'Giữa', type: 'Danh từ' },
    { word: '～や～[など]', reading: '～や～[など]', romaji: '~ya~[nado]', meaning: '~ và ~ [v.v]', type: 'Trợ từ' },
    { word: 'いちばん～', reading: 'いちばん～', romaji: 'ichiban~', meaning: '~ nhất', type: 'Phó từ' },
    { word: '～段目', reading: '～だんめ', romaji: '~danme', meaning: 'Ngăn thứ ~', type: 'Hậu tố' }
  ],
  11: [
    { word: 'りんご', reading: 'りんご', romaji: 'ringo', meaning: 'Quả táo', type: 'Danh từ' },
    { word: 'みかん', reading: 'みかん', romaji: 'mikan', meaning: 'Quả quýt', type: 'Danh từ' },
    { word: 'サンドイッチ', reading: 'サンドイッチ', romaji: 'sandoitchi', meaning: 'Bánh sandwich', type: 'Danh từ' },
    { word: 'カレー[ライス]', reading: 'カレー[ライス]', romaji: 'karee[raisu]', meaning: 'Cơm cà ri', type: 'Danh từ' },
    { word: 'アイスクリーム', reading: 'アイスクリーム', romaji: 'aisukuriimu', meaning: 'Kem', type: 'Danh từ' },
    { word: '切手', reading: 'きって', romaji: 'kitte', meaning: 'Tem', type: 'Danh từ' },
    { word: 'はがき', reading: 'はがき', romaji: 'hagaki', meaning: 'Bưu thiếp', type: 'Danh từ' },
    { word: '封筒', reading: 'ふうとう', romaji: 'fuutou', meaning: 'Phong bì', type: 'Danh từ' },
    { word: '速達', reading: 'そくたつ', romaji: 'sokutatsu', meaning: 'Chuyển phát nhanh', type: 'Danh từ' },
    { word: '書留', reading: 'かきとめ', romaji: 'kakitome', meaning: 'Thư bảo đảm', type: 'Danh từ' },
    { word: 'エアメール（航空便）', reading: 'エアメール（こうくうびん）', romaji: 'eameeru(koukuubin)', meaning: 'Thư máy bay', type: 'Danh từ' },
    { word: '船便', reading: 'ふなびん', romaji: 'funabin', meaning: 'Gửi bằng đường tàu', type: 'Danh từ' },
    { word: '両親', reading: 'りょうしん', romaji: 'ryoushin', meaning: 'Bố mẹ', type: 'Danh từ' },
    { word: '兄弟', reading: 'きょうだい', romaji: 'kyoudai', meaning: 'Anh em', type: 'Danh từ' },
    { word: '兄', reading: 'あに', romaji: 'ani', meaning: 'Anh trai (mình)', type: 'Danh từ' },
    { word: 'お兄さん', reading: 'おにいさん', romaji: 'oniisan', meaning: 'Anh trai (người khác)', type: 'Danh từ' },
    { word: '姉', reading: 'あね', romaji: 'ane', meaning: 'Chị gái (mình)', type: 'Danh từ' },
    { word: 'お姉さん', reading: 'おねえさん', romaji: 'oneesan', meaning: 'Chị gái (người khác)', type: 'Danh từ' },
    { word: '弟', reading: 'おとうと', romaji: 'otouto', meaning: 'Em trai (mình)', type: 'Danh từ' },
    { word: '弟さん', reading: 'おとうとさん', romaji: 'otoutosan', meaning: 'Em trai (người khác)', type: 'Danh từ' },
    { word: '妹', reading: 'いもうと', romaji: 'imouto', meaning: 'Em gái (mình)', type: 'Danh từ' },
    { word: '妹さん', reading: 'いもうとさん', romaji: 'imoutosan', meaning: 'Em gái (người khác)', type: 'Danh từ' },
    { word: '外国', reading: 'がいこく', romaji: 'gaikoku', meaning: 'Nước ngoài', type: 'Danh từ' },
    { word: '留学生', reading: 'りゅうがくせい', romaji: 'ryuugakusei', meaning: 'Lưu học sinh', type: 'Danh từ' },
    { word: 'クラス', reading: 'クラス', romaji: 'kurasu', meaning: 'Lớp học', type: 'Danh từ' },
    { word: '～時間', reading: '～じかん', romaji: '~jikan', meaning: '~ tiếng', type: 'Hậu tố' },
    { word: '～週間', reading: '～しゅうかん', romaji: '~shuukan', meaning: '~ tuần', type: 'Hậu tố' },
    { word: '～か月', reading: '～かげつ', romaji: '~kagetsu', meaning: '~ tháng', type: 'Hậu tố' },
    { word: '～年', reading: '～ねん', romaji: '~nen', meaning: '~ năm', type: 'Hậu tố' },
    { word: '～ぐらい', reading: '～ぐらい', romaji: '~gurai', meaning: 'Khoảng ~', type: 'Phó từ' },
    { word: 'どのくらい', reading: 'どのくらい', romaji: 'dono kurai', meaning: 'Bao lâu', type: 'Từ để hỏi' },
    { word: '全部で', reading: 'ぜんぶで', romaji: 'zenbude', meaning: 'Tổng cộng', type: 'Phó từ' },
    { word: 'みんな', reading: 'みんな', romaji: 'minna', meaning: 'Tất cả', type: 'Đại từ' },
    { word: '～だけ', reading: '～だけ', romaji: '~dake', meaning: 'Chỉ ~', type: 'Trợ từ' },
    { word: 'かしこまりました', reading: 'かしこまりました', romaji: 'kashikomarimashita', meaning: 'Tôi đã hiểu', type: 'Mẫu câu' }
  ],
  12: [
    { word: '簡単[な]', reading: 'かんたん[な]', romaji: 'kantan[na]', meaning: 'Đơn giản, dễ', type: 'Tính từ な' },
    { word: '近い', reading: 'ちかい', romaji: 'chikai', meaning: 'Gần', type: 'Tính từ い' },
    { word: '遠い', reading: 'とおい', romaji: 'tooi', meaning: 'Xa', type: 'Tính từ い' },
    { word: '速い / 早い', reading: 'はやい', romaji: 'hayai', meaning: 'Nhanh / Sớm', type: 'Tính từ い' },
    { word: '遅い', reading: 'おそい', romaji: 'osoi', meaning: 'Chậm, muộn', type: 'Tính từ い' },
    { word: '多い（人が～）', reading: 'おおい（ひとが～）', romaji: 'ooi (hito ga~)', meaning: 'Nhiều (người)', type: 'Tính từ い' },
    { word: '少ない（人が～）', reading: 'すくない（ひとが～）', romaji: 'sukunai (hito ga~)', meaning: 'Ít (người)', type: 'Tính từ い' },
    { word: '暖かい / 温かい', reading: 'あたたかい', romaji: 'atatakai', meaning: 'Ấm', type: 'Tính từ い' },
    { word: '涼しい', reading: 'すずしい', romaji: 'suzushii', meaning: 'Mát mẻ', type: 'Tính từ い' },
    { word: '甘い', reading: 'あまい', romaji: 'amai', meaning: 'Ngọt', type: 'Tính từ い' },
    { word: '辛い', reading: 'からい', romaji: 'karai', meaning: 'Cay', type: 'Tính từ い' },
    { word: '重い', reading: 'おもい', romaji: 'omoi', meaning: 'Nặng', type: 'Tính từ い' },
    { word: '軽い', reading: 'かるい', romaji: 'karui', meaning: 'Nhẹ', type: 'Tính từ い' },
    { word: 'いい（コーヒーが～）', reading: 'いい（コーヒーが～）', romaji: 'ii (koohii ga~)', meaning: 'Thích (cà phê hơn)', type: 'Tính từ い' },
    { word: '季節', reading: 'きせつ', romaji: 'kisetsu', meaning: 'Mùa', type: 'Danh từ' },
    { word: '春', reading: 'はる', romaji: 'haru', meaning: 'Mùa xuân', type: 'Danh từ' },
    { word: '夏', reading: 'なつ', romaji: 'natsu', meaning: 'Mùa hè', type: 'Danh từ' },
    { word: '秋', reading: 'あき', romaji: 'aki', meaning: 'Mùa thu', type: 'Danh từ' },
    { word: '冬', reading: 'ふゆ', romaji: 'fuyu', meaning: 'Mùa đông', type: 'Danh từ' },
    { word: '天気', reading: 'てんき', romaji: 'tenki', meaning: 'Thời tiết', type: 'Danh từ' },
    { word: '雨', reading: 'あめ', romaji: 'ame', meaning: 'Mưa', type: 'Danh từ' },
    { word: '雪', reading: 'ゆき', romaji: 'yuki', meaning: 'Tuyết', type: 'Danh từ' },
    { word: '曇り', reading: 'くもり', romaji: 'kumori', meaning: 'Có mây', type: 'Danh từ' },
    { word: 'ホテル', reading: 'ホテル', romaji: 'hoteru', meaning: 'Khách sạn', type: 'Danh từ' },
    { word: '空港', reading: 'くうこう', romaji: 'kuukou', meaning: 'Sân bay', type: 'Danh từ' },
    { word: '海', reading: 'うみ', romaji: 'umi', meaning: 'Biển', type: 'Danh từ' },
    { word: '世界', reading: 'せかい', romaji: 'sekai', meaning: 'Thế giới', type: 'Danh từ' },
    { word: 'パーティー', reading: 'パーティー', romaji: 'paatii', meaning: 'Bữa tiệc', type: 'Danh từ' },
    { word: 'お祭り', reading: 'おまつり', romaji: 'omatsuri', meaning: 'Lễ hội', type: 'Danh từ' },
    { word: '試験', reading: 'しけん', romaji: 'shiken', meaning: 'Kỳ thi', type: 'Danh từ' },
    { word: 'すき焼き', reading: 'すきやき', romaji: 'sukiyaki', meaning: 'Thịt bò nấu rau', type: 'Danh từ' },
    { word: '刺身', reading: 'さしみ', romaji: 'sashimi', meaning: 'Gỏi cá', type: 'Danh từ' },
    { word: 'おすし', reading: 'おすし', romaji: 'osushi', meaning: 'Sushi', type: 'Danh từ' },
    { word: 'てんぷら', reading: 'てんぷら', romaji: 'tenpura', meaning: 'Hải sản/rau tẩm bột chiên', type: 'Danh từ' },
    { word: '生け花', reading: 'いけばな', romaji: 'ikebana', meaning: 'Nghệ thuật cắm hoa', type: 'Danh từ' },
    { word: '紅葉', reading: 'もみじ', romaji: 'momiji', meaning: 'Lá đỏ', type: 'Danh từ' },
    { word: 'どちら', reading: 'どちら', romaji: 'dochira', meaning: 'Cái nào', type: 'Từ để hỏi' },
    { word: 'どちらも', reading: 'どちらも', romaji: 'dochiramo', meaning: 'Cả hai', type: 'Đại từ' },
    { word: 'ずっと', reading: 'ずっと', romaji: 'zutto', meaning: 'Hơn hẳn', type: 'Phó từ' },
    { word: '初めて', reading: 'はじめて', romaji: 'hajimete', meaning: 'Lần đầu tiên', type: 'Phó từ' }
  ]
};

// Evaluate the exported code to a JS module
let updatedCode = code;

// Replace each words array with the merged words array
const lines = updatedCode.split('\\n');
let currentLessonId = -1;
let insideWords = false;

// Gather existing words per lesson
const existingWordsByLesson = {};
for (let i = 1; i <= 12; i++) existingWordsByLesson[i] = [];

for (const line of lines) {
  const idMatch = line.match(/\\s*id:\\s*(\\d+),/);
  if (idMatch && !line.includes('L')) {
    currentLessonId = parseInt(idMatch[1], 10);
  }
  if (line.includes('words: [')) {
    insideWords = true;
  }
  if (insideWords && line.includes("word: '")) {
    const wordMatch = line.match(/word:\\s*'([^']+)'/);
    if (wordMatch && currentLessonId !== -1) {
      existingWordsByLesson[currentLessonId].push(wordMatch[1]);
    }
  }
  if (insideWords && line.includes('],')) {
    insideWords = false;
  }
}

// Now inject
let outputLines = [];
currentLessonId = -1;
insideWords = false;

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];
  outputLines.push(line);
  
  const idMatch = line.match(/\\s*id:\\s*(\\d+),/);
  if (idMatch && !line.includes('L')) {
    currentLessonId = parseInt(idMatch[1], 10);
  }
  
  if (line.includes('words: [')) {
    insideWords = true;
  }
  
  if (insideWords && line.match(/^\\s*\\],/)) {
    // We are at the end of the words array for currentLessonId
    const wordsToAdd = extraWords[currentLessonId];
    if (wordsToAdd) {
      const existing = existingWordsByLesson[currentLessonId] || [];
      let nextNum = existing.length + 1;
      
      let injectedLines = [];
      for (const w of wordsToAdd) {
        if (!existing.includes(w.word)) {
          const strNum = nextNum < 10 ? '0' + nextNum : nextNum.toString();
          const newLine = "      { id: 'L" + currentLessonId + "_" + strNum + "', word: '" + w.word + "', reading: '" + w.reading + "', romaji: '" + w.romaji + "', meaning: '" + w.meaning + "', type: '" + w.type + "' },";
          injectedLines.push(newLine);
          nextNum++;
        }
      }
      
      // Insert injectedLines BEFORE the '],' line
      if (injectedLines.length > 0) {
        outputLines.pop(); // Remove '],'
        outputLines.push(...injectedLines);
        outputLines.push(line); // Add '],' back
      }
    }
    insideWords = false;
  }
}

updatedCode = outputLines.join('\\n');

fs.writeFileSync(filePath, updatedCode, 'utf8');
console.log('Successfully injected missing words into all lessons.');
